apiVersion: v1
kind: ReplicationController
metadata:
  name: fps-rc-machine
  labels:
    app: fps-rc-machine
    type: front-end
spec:
  template:
    metadata:
      name: fps-pod-rc-machine
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
