apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment1
  labels:
    app: myapp1
    type: front-end1
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp1
        type: front-end1
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end1
      app: myapp1