##########################
# Splunk Deployment Server
##########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-deployment-server
  labels:
    type: front-end1
    app: myapp
spec:
  selector:
    matchLabels:
      type: front-end1
      app: myapp
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
    name: myapp-pod
    labels:
      app: myapp
      type: front-end1
    spec:
      containers:
      - name: splunk-deployment-server
        image: splunk/splunk:latest
        env:
        - name: SPLUNK_INDEX
          value: myindex
        ports:
          - name: splunk-api
            containerPort: 8089
            protocol: TCP
          - name: splunk-web
            containerPort: 8000
            protocol: TCP
